### ISSUE TITLE
sessionVarName

### ISSUE THREAD

**Issue by ric128** [marqu3s/yii2-behaviors#3]
Hi Marqu3s
I tried to change the "sessionVarName""GridFilters" to "myOwnNameGridFilters" but it doesn't work.
Why?
or how can I change the sessionVarName?
Thank you.

**Comment by marqu3s** [comment]
Hi!

Can you show me your code?

Atenciosamente,
João Marques

Em 22 de fev de 2018 10:34 -0300, ric128 <notifications@github.com> escreveu:

**Comment by ric128** [comment]
**This works**

class BncCuentasSearch extends BncCuentas
{
	
    public function behaviors()
    {
      return [
        'saveGridFilters' =>[
          'class' => SaveGridFiltersBehavior::className(),
          'sessionVarName' => self::className() . 'GridFilters'
        ],
        'saveGridPage' =>[
          'class' => SaveGridPaginationBehavior::className(),
          'sessionVarName' => self::className() . 'GridPage'
        ]
      ];
    }

    public function search($params)
    {
    	$this->load($params);

    	$dataProvider= new SqlDataProvider([...........
    	
        $dataProvider = $this->loadWithFilters($params, $dataProvider); 
    	$dataProvider->pagination->page = $this->getGridPage();
    	
    	return $dataProvider;
    }


**This doesn't work.**

class BncCuentasSearch extends BncCuentas
{
	
    public function behaviors()
    {
      return [
        'saveGridFilters' =>[
          'class' => SaveGridFiltersBehavior::className(),
          'sessionVarName' => self::className() . 'MyOwnNameGridFilters'
        ],
        'saveGridPage' =>[
          'class' => SaveGridPaginationBehavior::className(),
          'sessionVarName' => self::className() . 'GridPage'
        ]
      ];
    }

    public function search($params)
    {
    	$this->load($params);

    	$dataProvider= new SqlDataProvider([...........
    	
        $dataProvider = $this->loadWithFilters($params, $dataProvider); 
    	$dataProvider->pagination->page = $this->getGridPage();
    	
    	return $dataProvider;
    }

**Comment by marqu3s** [comment]
No interaction in a long time.

**Comment by marqu3s** [comment]
No interaction in a long time.
