### ISSUE TITLE
can't apply default filters

### ISSUE THREAD

**Issue by ghpeppe** [marqu3s/yii2-behaviors#7]
Usually, to apply default filter condition to the grid you just insert a row before the "load" command with the needed values:
```
        $this->doc_ruolo = 'PA';
        $this->load($params); // "loadWithFilters" in the case
```
This method doesn't run with the extension and the defined filters were ignored.
How can I achieve the goal?

**Comment by ghpeppe** [comment]
The above code is right; there was a mistake in the "rules" function. Btw the problem is not solved.
- The code sets a default filter on field X and it's applied opening the grid.
- When I manually set a filter on grid's field Z it's applied correctly too, but the filter on field X is removed.

I think the default filters would be removed only when the user sets something different on that field.
It seems this is not a problem specific for this extension but the yii platform; however adding a default filter managing to the extension would be a good thing.

**Comment by marqu3s** [comment]
Hi!
I’ve been very busy but I’ll take a look as soon as possible.

Atenciosamente,
João Marques
Em 31 de out de 2018 05:15 -0300, Peppe <notifications@github.com> escreveu:

**Comment by marqu3s** [comment]
Sorry for return back to you at that time. Closing this since it was posted a long time ago.
